### ISSUE TITLE
[Task]: Fix bal commands according to SLBeta4 changes

### ISSUE THREAD

**Issue by LakshanSS** [ballerina-platform/ballerina-extended-library#128]
### Task Description

Do changes in all connector build workflows according to the following
1. - https://github.com/ballerina-platform/ballerina-spec/issues/965
2. - https://github.com/ballerina-platform/ballerina-spec/issues/966
3. - https://github.com/ballerina-platform/ballerina-lang/issues/33256
4. - Remove `return;` which was explicitly added inside  functions
5. - https://github.com/ballerina-platform/ballerina-extended-library/issues/133
6. - Change release workflow to skip tests. (just `ball pack`)

### Connectors

- [ ] Github
- [ ] Twilio
- [ ] GSheet
- [ ] Gmail
- [x] Slack
- [x] Google Calendar
- [x] Salesforce
- [x] Netsuite
- [ ] Gdrive
- [ ] Azure Event Hubs
- [x] Azure Cosmos DB
- [ ] Azure Service Bus
- [ ] Azure Storage Service (File, Blob)
- [x] MongoDB
- [ ] Redis
- [ ] AWS S3
- [ ] AWS SQS
- [x] People API
- [ ] MSOneDrive
- [ ] MSExcel
- [ ] Twitter
- [x] MSTeams
- [x] Azure AD
- [ ] MSCalendar
- [ ] MS Outlook.Mail
- [ ] MS OneNote
- [ ] SnowFlake Driver
- [ ] AWS SES
- [ ] OpenAPI Connectors
