### ISSUE TITLE
[Epic]: Revamp Azure Service Bus connector

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-extended-library#14]
### Connector Name

module/azure-servicebus (Azure Servicebus)

### Epic description

Currently, ASB [1] returns a handle object on createSender & createReceiver operations. This handle object is used in other remote functions like send, receive, sendBatch, receiveBatch etc. But returning a handle is not considered a good practice.

So the objective of this revamp is to eliminate the usage/return of handle object & introducing pooling functionality.

### References
[1] https://github.com/ballerina-platform/module-ballerinax-azure-service-bus

### Related tasks

- [X] Research on connecter space for the feasibility of returning a Ballerina record instead of a handle https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/39 https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/44 https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/46 
- [X] Feasibility of merging operations like  `createSender` with `send` & `createReceiver` with `receive`
https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/39 https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/44 https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/46
- [X] Implementing a connection pool for sender & receiver objects.
https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/39 https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/44 https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/46
- [x]  Detect an open connection in Azure service bus. 
https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/39 https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/44 https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/46
- [X] Two client approach for ASB (MessageSender & MessageReceiver) 
https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/39 https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/44 https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/46
- [x] Update samples & test cases related.
https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/44 https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/46
- [x] Address review changes  https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/46
- [x] Migrate the connector on SLbeta3 https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/46
- [x]  Push to staging https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/46
