### ISSUE TITLE
[Epic]: Design and Implement GraphQL to Ballerina Client Generator

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-extended-library#15]
### Connector Name

other (None Listed Above)

### Epic description

[GraphQL](https://graphql.org) is a query language for APIs and a runtime for fulfilling those queries with your existing data. GraphQL provides a complete and understandable description of the data in your API, gives clients the power to ask for exactly what they need and nothing more, makes it easier to evolve APIs over time, and enables powerful developer tools.
Currently we don't have a tool to generate a GraphQL Client connector based on a GraphQL API specification for different vendors. 

### Related tasks

- [x] **Research on GraphQL domain** 
https://github.com/wso2-enterprise/choreo/issues/7881
- [x] **Study the GraphQL specification**
https://github.com/wso2-enterprise/choreo/issues/7885
- [x] **Prepare design document**
https://github.com/wso2-enterprise/choreo/issues/7883
- [x] **Prepare a mapping between GraphQL & Ballerina**
https://github.com/wso2-enterprise/choreo/issues/7884
- [x] **Implement sample Ballerina conectors for different API vendors using GraphQL API specifications**
https://github.com/wso2-enterprise/choreo/issues/7887
https://github.com/wso2-enterprise/choreo/issues/7886
- [x] **Try out different queries covering GraphQL advanced concepts & user scenarios**
https://github.com/wso2-enterprise/choreo/issues/7889
- [x] **Research on available GraphQL parsers**
https://github.com/wso2-enterprise/choreo/issues/7933
https://github.com/ballerina-platform/ballerina-extended-library/issues/16
- [x] **Implement a Java wrapper to process the record representation of a GraphQL query**
https://github.com/wso2-enterprise/choreo/issues/8141
https://github.com/ballerina-platform/ballerina-extended-library/issues/17
- [x] **Do a market research on  currently available GraphQL clients and VScode plugins**
https://github.com/ballerina-platform/ballerina-extended-library/issues/89
- [x] **Implement a sample implementation for [GraphQL-Kotlin client](https://github.com/ExpediaGroup/graphql-kotlin/) & explore the user experience it provides**
https://github.com/ballerina-platform/ballerina-extended-library/issues/125
- [x] **Create a proposal for the new design of Ballerina GraphQL connector generator and language level developments**
https://github.com/ballerina-platform/ballerina-extended-library/issues/118
- [x] **Implement the tool that can generate GraphQL client connectors using GraphQL API specifications**

### [Milestone Plan](https://docs.google.com/document/d/177u4l-nrqdqRdVtiJblBKFukvZWxXc6Nk1sxPnRN3rU/edit?usp=sharing)

- [x] **Milestone I - Nov 26, 2021**
  - [x] **Validation (Feature/Task)** https://github.com/ballerina-platform/ballerina-extended-library/issues/148
    - [x] **Background research (Sub Task)**
    - [x] **Implement SDL Validator (Sub Task)**
    - [x] **Implement Query Validator (Sub Task)**
    - [x] **Implement introspection support to generate SDL in runtime (Sub Task)** https://github.com/ballerina-platform/ballerina-extended-library/issues/168
  - [x] **QueryReader (Feature/Task)** https://github.com/ballerina-platform/ballerina-extended-library/issues/152
    - [x] **Background research (Sub Task)**
    - [x] **Implement GraphQL Query reader (Sub Task)**
  - [x] **SpecReader (Feature/Task)** https://github.com/ballerina-platform/ballerina-extended-library/issues/151
    - [x] **Background research (Sub Task)**
    - [x] **Implement GraphQL schema (SDL) reader (Sub Task)**

- [x] **Milestone II - Dec 10, 2021**
  - [x] **ClientGenerator (Feature/Task)**
    - [x] **Background research (Sub Task)**
    - [x] **Implement utils for Ballerina syntax tree generation** https://github.com/ballerina-platform/ballerina-extended-library/issues/177
    - [x] **Implement function signature generator (Sub Task)** https://github.com/ballerina-platform/ballerina-extended-library/issues/184
    - [x] **Implement function return type generator (Sub Task)** https://github.com/ballerina-platform/ballerina-extended-library/issues/186
    - [x] **Implement function body generator (Sub Task)** https://github.com/ballerina-platform/ballerina-extended-library/issues/185
    - [x] **Implement util generator (Sub Task)** https://github.com/ballerina-platform/ballerina-extended-library/issues/223
    - [x] **Implement record generator (Sub Task)** https://github.com/ballerina-platform/ballerina-extended-library/issues/178
    - [x] **Implement auth config generator (Sub Task)** https://github.com/ballerina-platform/ballerina-extended-library/issues/215
    - [x] **Implement diagnostic for graphql command errors in GraphQL Client Generation Tool (Sub Task)** https://github.com/ballerina-platform/ballerina-extended-library/issues/231

  - [x] **Write unit tests for the GraphQL client generation tool**https://github.com/ballerina-platform/ballerina-extended-library/issues/285
  - [x] **Complete Command line tool implementation (Final Deliverable)**
  
### Architecture of the Client Generator
![Architecture](https://user-images.githubusercontent.com/34184297/141244306-d11a79cc-e4d9-406f-bf7c-ac1d75cf345c.png)

**Comment by RolandHewage** [comment]
Closing this issue since all the tasks are completed and added to Ballerina distribution
