### ISSUE TITLE
[Task]: Study on Salesforce Integrations

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-extended-library#150]
### Connector Name

module/salesforce (Salesforce)

### Task Description

- [ ] - Overview of Salesforce APIs
- [ ] -  Using SOAP API to Integrate with Enterprise Apps
- [ ] - Creating Lightweight Integrations using REST API
- [ ] - Bulk API in Salesforce
- [ ] - Consuming External Services via Apex Callouts
- [ ] - Calling External Webservice from Lightning Web Components
- [ ] - Streaming API- PushTopics, Platform Events, Change Data Capture
- [ ] - Calling External Webservice from Aura Components
- [ ] - Fetching Data from Salesforce via External System
- [ ] - Sending Data from Salesforce to Java Application using Streaming API

**Comment by sachinira** [comment]
The document maintained to record the important knowledge and suggestions when following the courses
https://docs.google.com/document/d/16NJzwiLKiuWxq_L6BmSQVeMmDCZ1ITywvopa02ewiio/edit?usp=sharing

**Comment by FittEyes** [comment]
Salesforce is a well-known name in the Customer Management Industry, offering 360-degree CRM and ERP solutions. Its Customer Relationship Management (CRM) services comprise top-tier SaaS services including Commerce Cloud, Sales Cloud, Service Cloud Data Cloud, Marketing Cloud, Community Cloud, Analytics Cloud, App Cloud, and IoT (Internet of Things), and it has over a hundred thousand delighted clients globally.
