### ISSUE TITLE
[Epic]: Revamping Choreo samples

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-extended-library#159]
### Connector Name

other (None Listed Above)

### Epic description

Revamping Choreo samples [1] contains a few steps.

[1] https://github.com/wso2-enterprise/choreo-samples

### Related tasks

- [x]  **Gradle project conversion**
- [x]  **Hash generation**
- [x] **Implement a build flow**
- [x]  **Validator for choreo samples**
- [x]  **Add `Package.md` files for templates**
- [x]  **Icon changes - New icons for integrations**
- [x] **Push packages  as templates to staging**
- [x]  **Documentation for repo**
- [x]  **Release to central**

**Comment by LakshanSS** [comment]
Closing since this is outdated.

It was addressed by https://github.com/wso2-enterprise/choreo-samples/pull/373
