### ISSUE TITLE
[Improvement]: Redis improvements

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-extended-library#160]
### Connector Name

module/redis (Redis)

### Epic description

Redis needs several improvements to be done. 
Refer to the below issues attached. 

### Related tasks

- [x] https://github.com/ballerina-platform/ballerina-extended-library/issues/33
- [ ] https://github.com/ballerina-platform/ballerina-extended-library/issues/32
- [x] https://github.com/ballerina-platform/ballerina-extended-library/issues/31

**Comment by aneeshafedo** [comment]
Track via the new issue #580
