### ISSUE TITLE
[Epic]: Design and implement Amazon SNS connector

### ISSUE THREAD

**Issue by kapilraajP** [ballerina-platform/ballerina-extended-library#19]
### Connector Name

other (None Listed Above)

### Epic description

Implementation of Amazon SNS connector in Swan Lake Beta 3

### Related tasks

- [x] **Research on connector space** 
- [x] **Develop the connector** 
- [x] **Write documentation and samples** 
- [ ] **Release the connector**
