### ISSUE TITLE
[Epic]: Redesign and Re-implement Salesforce connectors

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-extended-library#229]
### Connector Name

module/salesforce (Salesforce)

### Epic description

Salesforce  customer relationship management (CRM) platform  with several products such as Commerce Cloud, Sales Cloud, Service Cloud, Data Cloud(including Jigsaw), Marketing Cloud, Community Cloud (including Chatter), Manufacturing Cloud, Analytics Cloud, App Cloud, Vaccine Cloud, IoT and Work.com with over 100,000 customers.It's products are mainly focused on  enterprise applications on customer service, marketing automation, analytics, and application development. 

The existing Ballerina connector for Salesforce contains 3 modules 
`salesforce` - Uses Salesforce REST API
`salesforce.soap` - Uses Salesforce SOAP API
`salesforce.bulk` - Uses Salesforce Bulk API

**Requirements**
- Redesign the connector such that it provides more user friendly customer experience
  * Provide dynamic input record types in runtime
  * Provide dynamic output record types
- Make the connector scalable to customized nature of Salesforce
- Extend the current functionalities provided by of the connector modules

**Initial research data**
- Initial discussions with Ballerina team on dynamic input and output record type creation
https://docs.google.com/document/d/1P12bi92MPvPOylblHhKfZMzArO4nXIdgwpCmIYBdqMA/edit#heading=h.tzfh4n9xdm4g

### Related tasks
- [x] **Research on Salesforce APIs**  https://github.com/ballerina-platform/ballerina-extended-library/issues/150
- [x] **Conduct a market research on available competitors** https://github.com/ballerina-platform/ballerina-extended-library/issues/218
- [x] **Prepare design document** https://docs.google.com/document/d/1PL1VcT4vw1FEwn7gY2kVSWukBxjvSedh9MVtW7vIqIs/edit?usp=sharing
- [x] **Prepare specification for the proposed solution** https://docs.google.com/document/d/1RJWjafSo9F-o3KP59n-ZUA8mA5mCOMLXjYd-isyRkNo/edit?usp=sharing
- [x] **Prepare POC for the design**
    - [x] Implement  improvement for current Choreo record generator for the generation of input records in CRMs
         - [x] Implement a LS-Extension service to extract a record out of the response from Salesforce metadata API    
       https://github.com/ballerina-platform/ballerina-extended-library/issues/357
       https://github.com/ballerina-platform/ballerina-extended-library/issues/94
         - [x] Extend the low-code editor UI for supporting a list of connectors to generate customized records
       https://github.com/ballerina-platform/ballerina-extended-library/issues/280

- [x] **Develop the connector and write documentation** 
     - [x] Change the module structure of the connector
     - [x] Implement java based operations to map return types of operations
     
- [x] **Write samples**
- [x] **Release the connector**
- [ ] **Develop integration templates for the connector**

**Comment by sachinira** [comment]
The documents with summary of findings in market research
https://docs.google.com/document/d/1wM4E84anzUfYssIDK_pG3hQ2Prf2OHatIZoNTm17JOU/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1lTVvC-Ty-Rh0mASJKj_X0PDGMbrvKEJ-02BPSCN98e4/edit?usp=sharing

**Comment by sachinira** [comment]
Closing this Epic as the Improvement for custom record generation CRM connector task is on hold. Please find further information [here](https://docs.google.com/document/d/1zY077IuINjxHdToDhJ1oZL9HvUebUwHOy3td4VbczW4/edit?usp=sharing)
