### ISSUE TITLE
[Epic]: [Choreo Samples] Listener Replacement with Async API Triggers

### ISSUE THREAD

**Issue by RolandHewage** [ballerina-platform/ballerina-extended-library#236]
### Connector Name

other (None Listed Above)

### Epic description

We came to an agreement to update the samples with Async API triggers as a solution to the issue [3]. The burden of manually registering the callback URL at the API side is given to the user in Async API triggers. The user doesn't need to provide a callback URL during the listener configuration in Async API triggers. For example refer [1] [2]. The user can obtain the Choreo callback URL after deployment and use it to manually register the listener in the API side. In the future if we really have a callback URL configuration requirement within the listener, we agreed to handle it within the listener init function itself. But this approach is not recommended and we will go forward with the Async API trigger approach. All the samples will be updated as soon as the Async API triggers are ready for use.

[1] https://github.com/ballerina-platform/asyncapi-triggers/blob/dcbc81bf52394a6cdcad7f881227fbd1e2240006/asyncapi/github/data_types.bal#L19
[2] https://github.com/ballerina-platform/asyncapi-triggers/blob/dcbc81bf52394a6cdcad7f881227fbd1e2240006/asyncapi/github/listener.bal#L25
[3] https://github.com/wso2-enterprise/choreo/issues/10217

The execution plan is summarized in the following sheet
https://docs.google.com/spreadsheets/d/1CVmNi8MBHdILbNPlFmmdQmSLuZAai3w7YYP_Vz1dLvQ/edit?usp=sharing

### Related tasks

- [x] **Salesforce New Lead to Google Sheets Row**  https://github.com/ballerina-platform/ballerina-extended-library/issues/240
- [x] **Google Sheets New Row to GitHub New Issue** https://github.com/ballerina-platform/ballerina-extended-library/issues/241
- [x] **Google Sheets Row Update to Gmail Message** https://github.com/ballerina-platform/ballerina-extended-library/issues/242
- [x] **Google Sheets New Row to Salesforce New Lead** https://github.com/ballerina-platform/ballerina-extended-library/issues/244
- [x] **Google Sheets New Row to Salesforce New Record** https://github.com/ballerina-platform/ballerina-extended-library/issues/245
- [x] **Google Sheets Row Update to Salesforce Record Update** https://github.com/ballerina-platform/ballerina-extended-library/issues/247
- [x] **Slack Channel New Message to Twilio SMS**https://github.com/ballerina-platform/ballerina-extended-library/issues/254
- [x] **Salesforce New Case to Google Sheets Row**https://github.com/ballerina-platform/ballerina-extended-library/issues/253
- [x] **Salesforce New Lead to Twilio SMS**https://github.com/ballerina-platform/ballerina-extended-library/issues/252
- [x] **Salesforce New Contact to Twilio SMS**https://github.com/ballerina-platform/ballerina-extended-library/issues/251
- [x] **Salesforce New Contact to NetSuite New Contact**https://github.com/ballerina-platform/ballerina-extended-library/issues/250
- [x] **Salesforce New Case to Google Sheets New Spreadsheet**https://github.com/ballerina-platform/ballerina-extended-library/issues/249
- [x] **GitHub Issue Assigned to SMS Notification**  https://github.com/ballerina-platform/ballerina-extended-library/issues/255
- [x] **GitHub Issue Assigned to Twilio SMS**  https://github.com/ballerina-platform/ballerina-extended-library/issues/256
- [x] **GitHub New Issue to Google Sheets Row**  https://github.com/ballerina-platform/ballerina-extended-library/issues/257
- [x] **GitHub New Release to Twilio SMS**  https://github.com/ballerina-platform/ballerina-extended-library/issues/258
- [x] **GitHub New Release to Slack Channel Message**  https://github.com/ballerina-platform/ballerina-extended-library/issues/259
- [x]  **Salesforce Hot Lead to Slack Channel Message** 
- [x] **Salesforce Update Record to Google Sheet New Row**
- [x] **Salesforce Opportunity Update to Slack**
- [x] **Salesforce Opportunity Closed-Won to Slack**
- [x] **Salesforce Opportunity Update to Twilio SMS**
- [x] **Salesforce New Record to Google Sheets Row**
- [x] **Salesforce Update Record to Google Sheet Update Row**

**Comment by RolandHewage** [comment]
Closing this issue since all the PRs are merged
