### ISSUE TITLE
[Epic]: Design and implement WSDL to Ballerina client generator

### ISSUE THREAD

**Issue by SanduDS** [ballerina-platform/ballerina-extended-library#24]
### Connector Name

other (None Listed Above)

### Epic description

WSDL is an XML based web service definition that provides the functionality of the web service exposed by the service provider. In many languages, clients can be created from WSDL and accessed.
Currently, Ballerina does not have a tool to generate client connectors from WSDL.

### Related tasks

- [ ] **Research on WSDL, SOAP, DOM and SAX domains** 
- [ ] **Prepare design document**
- [ ] **Prepare mapping between WSDL and Ballerina**

**Comment by Chuhaa** [comment]
As we have following blocker issues in ballerina xmldata module, we hold this task until get the fix.

1. https://github.com/ballerina-platform/ballerina-standard-library/issues/1900
2. https://github.com/ballerina-platform/ballerina-standard-library/issues/1902
3. https://github.com/ballerina-platform/ballerina-standard-library/issues/1918

**Comment by Chuhaa** [comment]
[Draft design document](https://docs.google.com/document/d/18FK5JRy6QSv-13K7eRv7os3WoxTCK8VkZb7D-_AXCi8/edit#heading=h.69x6uzi2sjr9)

**Comment by abeykoon** [comment]
This will be onHold until we get required features from Ballerina core.
