### ISSUE TITLE
[Epic]: Add connector code coverage information to workflows

### ISSUE THREAD

**Issue by RolandHewage** [ballerina-platform/ballerina-extended-library#271]
### Connector Name

other (None Listed Above)

### Epic description

We need to come up with an approach to view the code coverage information of all the connectors. We can generate the code coverage information by using the following command. 
```
$ bal test --code-coverage
```
These information are sumarized in a `test_results.json` file generated. We can use this command in the workflows to obtain the code coverage information.

### Related tasks

Add the code coverage information to workflows in the following connectors

- [x] **Google Sheets**
- [x] **Google Calendar**
- [x] **Google Drive**
- [x] **Google People**
- [x] **Gmail**
- [x] **Salesforce**
- [x] **CosmosDB**
- [x] **Netsuite**
- [x] **Azure Event Hub**
- [x] **Azure Service Bus**
- [x] **Azure Storage Service**
- [x] **Azure AD** - No Tests
- [x] **GitHub**
- [x] **Twilio**
- [x] **Twitter**
- [x] **Slack**
- [x] **MongoDB**
- [x] **Redis**
- [x] **AWS S3**
- [x] **AWS SQS**
- [x] **Snowflake.Driver** - No Tests
- [x] **Microsoft OneDrive**
- [x] **Microsoft Excel**
- [x] **Microsoft Teams** - No Tests
- [x] **Microsoft Outlook Calendar**
- [x] **Microsoft Outlook Mail**
- [x] **Microsoft OneNote**
- [x] **AWS SES**
- [x] **AWS SNS**
- [x] **AWS DynamoDB**
- [x] **AWS SimpleDB**
- [x] **PeopleHR** - No Tests

**Comment by RolandHewage** [comment]
The code coverage information are summarized in the following sheet.
https://docs.google.com/spreadsheets/d/1tID4KNJR196upht9DSk7hUuqpbqwHEW1bGOZWrrEDyc/edit?usp=sharing
