### ISSUE TITLE
[Epic]: Design and Implement Choreo Data Explorer 

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-extended-library#35]
### Connector Name

other (None Listed Above)

### Epic description

Implement Data Explorer in Choreo to test connections and query data prior to integration implementation. 

#### Functional Requirements

- Test connections created before deploying the integration
- 	Connections can be 
          - RDBMS - provides a DBConsole experience
          - GraphQL  - GraphQL Editor experience (https://lucasconstantino.github.io/graphiql-online/)
          - HTTP REST API - Swagger and try it
          - Connectors with selecting an available connector type - Ability to execute some methods in the connector.
- Build and execute queries to see whether the query returns the expected results and then copy the tried out  query to the integration
- Allow users to browse databases and schemas within the choreo, giving a seamless experience.

### Design Docs
![Data Explorer V2](https://user-images.githubusercontent.com/34091327/158332892-8d46d38a-cffc-4c7a-86b7-0bf0e12ea2da.jpg)

* v1 - [see here](https://docs.google.com/document/d/1VrqVq59Cp_2ZKnIf7c1LVVDqAe3jOzfNTVCauetFDKU/edit#) 
* v2 (latest) - [see here](https://docs.google.com/document/d/17-duUC5-Ab0jsjjkhEVhej8SRsDlGaqdXC6KuNOYyUk/edit?usp=sharing)

### Related tasks

- [x] https://github.com/ballerina-platform/ballerina-extended-library/issues/67
- [x] https://github.com/ballerina-platform/ballerina-extended-library/issues/114
- [x] https://github.com/ballerina-platform/ballerina-extended-library/issues/146
- [x] https://github.com/ballerina-platform/ballerina-extended-library/issues/221
- [x] https://github.com/ballerina-platform/ballerina-extended-library/issues/321
- [x] https://github.com/ballerina-platform/ballerina-extended-library/issues/387
- [x] https://github.com/ballerina-platform/ballerina-extended-library/issues/322
- [ ] https://github.com/ballerina-platform/ballerina-extended-library/issues/323
- [ ] https://github.com/ballerina-platform/ballerina-extended-library/issues/324
- [x] https://github.com/ballerina-platform/ballerina-extended-library/issues/397

**Comment by abeykoon** [comment]
This feature got deviated and we decided not to contribute it. 
Idea is to find suitable VS code extension project which provides explore capability and contribute. 
Hence closing.
