### ISSUE TITLE
[Epic]: SAP Connector Development

### ISSUE THREAD

**Issue by SanduDS** [ballerina-platform/ballerina-extended-library#384]
### Connector Name

other (None Listed Above)

### Epic description

This relates to all SAP R&D for SAP Ballerina connector

### Related tasks
- [x] **[Initial Planning for SAP integeration through Ballerina](https://github.com/ballerina-platform/ballerina-extended-library/issues/200)** 
- [x] **[Research work on SAP classical connection apporoches via RFC for BAPI, IDOC](https://github.com/ballerina-platform/ballerina-extended-library/issues/385)**
- [x] **[POC for Balleirna connector for invoking Remotely enabled function modules in SAP](https://github.com/ballerina-platform/ballerina-extended-library/issues/409)**
- [x] **[Documentation SAP R&D progress and future plans](https://github.com/ballerina-platform/ballerina-extended-library/issues/410)**
- [x] **[Research work on SAP extension related latest apporches for connector development](https://github.com/ballerina-platform/ballerina-extended-library/issues/435)**

**Comment by SanduDS** [comment]
closing as completed
