### ISSUE TITLE
[Epic]: Migrate connectors on SLAlpha5 branch to SLBeta3 with backward compatibility 

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-extended-library#42]
### Epic description

Migrate all existing connectors [1] from branch slalpha5 to slbeta3 with no breaking changes.

- Try building all connectors on the Alpha5 branch with the Beta3 pack. 
- Fix errors where necessary in all connectors.
- Version bump the connector in all connectors.
- Update workflow files to use `@nightly` in all connectors.
- Push all connectors to staging central.

### Related tasks

Complete the migration in the following connectors. Refer to the sheet [2]

- [x] Github
- [x] GSheets
- [x] GDrive
- [x] Gmail
- [x] GCalendar
- [x] GPeople
- [x] Salesforce
- [x] Twilio
- [x] Slack
- [x] OneDrive
- [x] Azure Eventhub
- [x] Azure Cosmosdb
- [x] Azure Files
- [x] Azure Blobs
- [x] Azure Service Bus
- [x] Mongodb
- [x] Redis
- [x] AWS S3
- [x] AWS SQS
- [x] Netsuite
- [x] Zoom
- [x] Spotify
- [x] Sendgrid
- [x] Medium
- [x] Leanix Integrationapi
- [x] Covid19
- [x] Worldbank API
- [x] OpenWeatherMap
- [x] MySQL
- [x] SMS by Choreo
- [x] Mail by Choreo
- [x] WhatsApp by Choreo

[1] https://github.com/wso2-enterprise/choreo-lang-server/blob/master/connectors/connectors.toml
[2] https://docs.google.com/spreadsheets/d/198CPB2upz3lTzGWzkCsiB-s66ObMXGdQ6mETjvAXs-0/edit#gid=0

**Comment by SkNuwanTissera** [comment]
<google-sheets-html-origin><style type="text/css"></style>

PR List
--
https://github.com/ballerina-platform/module-ballerinax-github/pull/153
https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/pull/194
https://github.com/ballerina-platform/module-ballerinax-googleapis.drive/pull/80
https://github.com/ballerina-platform/module-ballerinax-googleapis.gmail/pull/145
https://github.com/ballerina-platform/module-ballerinax-googleapis.calendar/pull/57
https://github.com/ballerina-platform/module-ballerinax-googleapis.people/pull/24
https://github.com/ballerina-platform/module-ballerinax-sfdc/pull/172
https://github.com/ballerina-platform/module-ballerinax-twilio/pull/125
https://github.com/ballerina-platform/module-ballerinax-slack/pull/62
https://github.com/ballerina-platform/module-ballerinax-microsoft.onedrive/pull/24
https://github.com/ballerina-platform/module-ballerinax-azure.eventhub/pull/45
https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb/pull/32
https://github.com/ballerina-platform/module-ballerinax-azure-storage-service/pull/25
https://github.com/ballerina-platform/module-ballerinax-azure-storage-service/pull/25
https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/pull/41
https://github.com/ballerina-platform/module-ballerinax-mongodb/pull/131
https://github.com/ballerina-platform/module-ballerinax-redis/pull/96
https://github.com/ballerina-platform/module-ballerinax-aws.s3/pull/66
https://github.com/ballerina-platform/module-ballerinax-aws.sqs/pull/46
https://github.com/ballerina-platform/module-ballerinax-netsuite/pull/39
https://github.com/ballerina-platform/ballerinax-openapi-connectors/pull/449
https://github.com/ballerina-platform/ballerinax-openapi-connectors/pull/449
https://github.com/ballerina-platform/ballerinax-openapi-connectors/pull/449
https://github.com/ballerina-platform/ballerinax-openapi-connectors/pull/449
https://github.com/ballerina-platform/ballerinax-openapi-connectors/pull/449
https://github.com/ballerina-platform/ballerinax-openapi-connectors/pull/449
https://github.com/ballerina-platform/ballerinax-openapi-connectors/pull/449
https://github.com/ballerina-platform/ballerinax-openapi-connectors/pull/449
https://github.com/indikasampath2000/module-choreo-sendsms/pull/1
https://github.com/indikasampath2000/module-choreo-sendemail/pull/1

**Comment by abeykoon** [comment]
HTTP
 SMTP
 POP
 IMAP

These 4 we can ignore, since it is coming with ballerina dist.

**Comment by abeykoon** [comment]
`WhatsApp by Choreo` This has not been onboarded.
