### ISSUE TITLE
[Feature]: Add Amadeus connectors

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-extended-library#428]
### Connector Name

connectors/openapi (Open API Connector)

### Suggested feature

Amadeus is a popular platform used to compare prices and book flights. We need a connector to easily communicate with the APIs exposed by them in Choreo. 

- [x] Amadeus Flight Search https://github.com/ballerina-platform/ballerina-extended-library/issues/415
- [x] Amadeus Flight Price https://github.com/ballerina-platform/ballerina-extended-library/issues/416
- [x] Amadeus Create Orders https://github.com/ballerina-platform/ballerina-extended-library/issues/417
