### ISSUE TITLE
[Epic]: Site24x7 complex monitors to Citrus Tests

### ISSUE THREAD

**Issue by SanduDS** [ballerina-platform/ballerina-extended-library#445]
### Connector Name

other (None Listed Above)

### Epic description

This task is to move Site24*7 test cases to citrus tests to avoid false unsuitability reports. 

### Related tasks

- [x] **Study the Citrus framework**https://github.com/ballerina-platform/ballerina-extended-library/issues/446
- [x] **Create project proposal** 
- [x] **Implement and Deploy Citrus** https://github.com/ballerina-platform/ballerina-extended-library/issues/458
- [x] **Change project structure to push in the existing Azure functions repository**
- [x] **Documentation**

**Comment by SanduDS** [comment]
closing as completed
