### ISSUE TITLE
[Task]: Update Slack channel occurrences with Discord

### ISSUE THREAD

**Issue by kasthuriraajan** [ballerina-platform/ballerina-extended-library#474]
### Connector Name

other (None Listed Above)

### Task Description

Update Slack channel occurrences with Discord from repo readme.md , package.md, module.md. Check all the places in all modules.

- [x] GitHub
- [x] Twilio
- [x] GSheet
- [x] Gmail
- [x] Slack
- [x] Google Calendar
- [x] Salesforce
- [x] Netsuite
- [x] Google Drive
- [x] Azure EventHub
- [x] CosmosDB
- [x] Azure Service Bus
- [x] Azure Storage Service
- [x] MongoDB
- [x] Redis
- [x] AWS S3
- [x] AWS SQS
- [x] Google People API
- [x] MS OneDrive
- [x] MS Excel
- [x] Twitter
- [x] MS Teams
- [x] Azure AD
- [x] Outlook Calendar
- [x] Outlook Mail
- [x] MS OneNote
- [x] SnowFlake Driver
- [x] AWS SES
- [x] AWS-SNS
- [x] AWS-DynamoDB
- [x] AWS-SimpleDB
- [x] PeopleHR
- [x] OpenAPI connectors

**Comment by LakshanSS** [comment]
@kasthuriraajan All the PRs are merged. They will be released with the upcoming iteration of the release

**Comment by kasthuriraajan** [comment]
Links updated and connectors released
