### ISSUE TITLE
[Epic]: Integrate security scans for Ballerina extended libraries

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-extended-library#536]
### Connector Name

other (None Listed Above)

### Epic description

Integrate security scans for source code and dependencies in Ballerina extended libraries, as suggested in the [Security](https://github.com/ballerina-platform/ballerina-extended-library/blob/main/docs/quality-assuarance-guide.md#security) section of the [extended library development process guide](https://github.com/ballerina-platform/ballerina-extended-library/blob/main/docs/quality-assuarance-guide.md) to proactively identify potential security vulnerabilities in the extended modules.

Here are few suggestions to start with 
- dependency vulnerability scans using [Trivy](https://github.com/aquasecurity/trivy)
- source code vulnerability scans using [Fossa](https://fossa.com/)

**Comment by NipunaRanasinghe** [comment]
This is to track the integration of the [Trivy](https://github.com/aquasecurity/trivy) vulnerability scanner for all the extended  libraries having native code and 3rd-party java dependencies

- [ ] [module-ballerinax-sfdc](https://github.com/ballerina-platform/module-ballerinax-sfdc)
- [ ] [module-ballerinax-azure-cosmosdb](https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb)
- [ ] [module-ballerinax-azure-service-bus](https://github.com/ballerina-platform/module-ballerinax-azure-service-bus)
- [ ] [module-ballerinax-mongodb](https://github.com/ballerina-platform/module-ballerinax-mongodb)
- [ ] [module-ballerinax-redis](https://github.com/ballerina-platform/module-ballerinax-redis)
- [ ] [module-ballerinax-twitter](https://github.com/ballerina-platform/module-ballerinax-twitter)
- [ ] [module-ballerinax-cdata.connect](https://github.com/ballerina-platform/module-ballerinax-cdata.connect)
- [ ] [module-ballerinax-snowflake](https://github.com/ballerina-platform/module-ballerinax-snowflake)

**Comment by NipunaRanasinghe** [comment]
Closing as completed
