### ISSUE TITLE
Automate examples verification in extended library repos

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-extended-library#539]
### Epic description

Currently we have a collection of ballerina examples (Ballerina packages / single files) in most of the extended library repos. However there's no proper approach taken to validate the samples against new module changes as well as any breaking impacts from the dependencies (i.e. breaking language changes). 

### Related tasks

To overcome the above issues, it will be better to
- [ ] keep a common directory structure in all the extended library repos for the examples, as proposed in https://github.com/ballerina-platform/ballerina-extended-library/blob/main/docs/module-contribution-guide.md#the-examples-directory-gradle-submoduleoptional
- [ ] integrate all the examples to CI/CD process so that we can validate for compile time and runtime issues in the examples, by building (and running) all samples within the above directory.

**Comment by nipunayf** [comment]
The first implementation phase of the feature considers the following modules.

- [ ] [module-ballerinax-sfdc](https://github.com/ballerina-platform/module-ballerinax-sfdc)
- [ ] [module-ballerinax-azure-cosmosdb](https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb)
- [ ] [module-ballerinax-azure-service-bus](https://github.com/ballerina-platform/module-ballerinax-azure-service-bus)
- [ ] [module-ballerinax-mongodb](https://github.com/ballerina-platform/module-ballerinax-mongodb)
- [ ] [module-ballerinax-redis](https://github.com/ballerina-platform/module-ballerinax-redis)
- [ ] [module-ballerinax-twitter](https://github.com/ballerina-platform/module-ballerinax-twitter)
- [ ] [module-ballerinax-cdata.connect](https://github.com/ballerina-platform/module-ballerinax-cdata.connect)
- [ ] [module-ballerinax-snowflake](https://github.com/ballerina-platform/module-ballerinax-snowflake)

**Comment by nipunayf** [comment]
Even though the following modules lack examples, their repositories have been restructured to maintain a consistent directory structure.

1. [module-ballerinax-github](https://github.com/ballerina-platform/module-ballerinax-github)
2. [module-ballerinax-azure-storage-service](https://github.com/ballerina-platform/module-ballerinax-azure-storage-service)
3. [module-ballerinax-mongodb](https://github.com/ballerina-platform/module-ballerinax-mongodb)
4. [module-ballerinax-aws.ses](https://github.com/ballerina-platform/module-ballerinax-aws.ses)
5. [module-ballerinax-peoplehr](https://github.com/ballerina-platform/module-ballerinax-peoplehr)
6. [module-ballerinax-aws.simpledb](https://github.com/ballerina-platform/module-ballerinax-aws.simpledb)
7. [module-ballerinax-aws.dynamodb](https://github.com/ballerina-platform/module-ballerinax-aws.dynamodb)

**Comment by aneeshafedo** [comment]
Closing since all the PRs sent are merged
