### ISSUE TITLE
[Task]: Add workflow in OpenAPI connectors to regenerate all the connectors available

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-extended-library#554]
### Connector Name

connectors/openapi (Open API Connector)

### Task Description

$subject
This is usefull in testing the openapi connectors against new OpenAPI tool version

**Comment by aneeshafedo** [comment]
task breakdown:

*   [ ] Re-generate all connectors with a given docker version
*   [ ] Re-generate all connectors with custom ballerina distribution build
*   [ ] Re-generate set of connectors using a given ballerina-distribution
*   [ ] Publish a report at the end of the workflow run
