### ISSUE TITLE
[Epic]: Design and implement AWS SES connector

### ISSUE THREAD

**Issue by kasthuriraajan** [ballerina-platform/ballerina-extended-library#60]
### Connector Name

module/aws-ses (AWS SES)

### Epic description

Existing AWS SES connector is in API v1 and has limited number of operations. It is decided to implement the connector using AWS SES API v2.

### Related tasks

- [x] **Research on API and connector space** 
- [x] **Develop the connector and write documentation** 
         https://github.com/ballerina-platform/ballerina-extended-library/issues/28
         https://github.com/wso2-enterprise/choreo/issues/8041
- [x] **Release the connector**
