### ISSUE TITLE
[Epic]: Design and implement AWS DynamoDB connector

### ISSUE THREAD

**Issue by kasthuriraajan** [ballerina-platform/ballerina-extended-library#61]
### Connector Name

other (None Listed Above)

### Epic description

It is decided to design and develop a ballerina connector for Amazon DynamoDB.

### Related tasks

- [x] **Research on API and connector space** 
- [x] **Prepare design document**
      https://github.com/ballerina-platform/ballerina-extended-library/issues/63
- [x] **Develop the connector and write documentation** 
      https://github.com/ballerina-platform/ballerina-extended-library/issues/62
- [x] **Release the connector**
